### ISSUE TITLE
do_amp_selfcal=False

### ISSUE THREAD

**Issue by DaleiliXAO** [jjtobin/auto_selfcal#13]
If do_amp_selfcal=False, there is an issue below. 
File "auto_selfcal.py", line 1116, in <module>
    generate_weblog(selfcal_library,solints,bands)
  File "selfcal_helpers.py", line 2155, in generate_weblog
    render_per_solint_QA_pages(sclib,solints,bands)
  File "selfcal_helpers.py", line 2426, in render_per_solint_QA_pages
    final_solint_to_plot=solints[band][final_solint_index+index_addition-1]
IndexError: list index out of range

**Comment by jjtobin** [comment]
Thanks for the report, I will see if I can address this soon. It looks like it should be a straightforward fix. Then you'd be able to regenerate the weblog by running 'regenerate_weblog.py'. In any event, your selfcal run finished, but it just failed in making the weblog.

**Comment by DaleiliXAO** [comment]
Thank you for your reply. Yes, making the weblog was failed. I run  'regenerate_weblog.py' but still failed. 
  File "regenerate_weblog.py", line 15, in <module>
    generate_weblog(selfcal_library,solints,bands)
  File "selfcal_helpers.py", line 2155, in generate_weblog
    render_per_solint_QA_pages(sclib,solints,bands)
  File "selfcal_helpers.py", line 2426, in render_per_solint_QA_pages
    final_solint_to_plot=solints[band][final_solint_index+index_addition-1]
IndexError: list index out of range

**Comment by jjtobin** [comment]
Yeah, I hadn't fixed anything yet, so that was expected to fail still. I wasn't able to reproduce the issue you're seeing, which might mean there's something peculiar with your data set that's throwing things off. 

I have a possible fix, but I wanted to understand what's triggering this problem a bit better, are you able to share your bands.pickle  selfcal_library.pickle  solints.pickle, from that I should be able to trigger the problem. Also if you're able to let me know what the dataset is (if it's not proprietary), I could run it locally to make sure I fixed the problem.

**Comment by DaleiliXAO** [comment]
The issue is fixed using updated selfcal_helpers.py and the weblog is regenerated. Thank you.
